<?php
$data['SiteTitle']=stripslashes($site_title);
$data['SiteCharset']=stripslashes($site_charset);
$data['SiteCopyrights']=stripslashes($site_copyrights);
$data['SiteKeywords']=stripslashes($site_keywords);
$data['SiteDescription']=stripslashes($site_description);
if(!empty($admin_email)){$data['AdminEmail']=$admin_email;}
$data['AdminCheckIp']=$admin_check_ip;
$data['AdminIpAddress']=$admin_ip_address;
$data['ProtectHtml']=$protect_html;
###############################################################################
###           PLEASE DO NOT CHANGE INFORMATION BELOW THIS COMMENT           ###
###############################################################################
$data['MaxRowsByPage']=50;
$data['UseSmsPin']=$use_smspin;
$data['UseTuringNumber']=$use_turing;
$data['TuringNumbers']=$use_numbers;
$data['TuringSize']=$turing_size;
$data['TuringQuality']=$turing_quality;
$data['TuringBackground']=$turing_bgfile;
$data['UseExtRegForm']=$use_extreg;
$data['DefaultLanguage']=$default_language;
$data['PassLen']=$passlen;
$data['PassAtt']=$passatt;
$data['Currency']=$currency;
$data['CurrSize']=$currsize;
$data['DateFormat']=$dateformat;
$data['SignupPays']=$signup_use;
$data['SignupBonus']=$signup_bonus;
$data['ReferralPays']=$affiliate_program;
$data['ReferralLevels']=$affiliate_levels;
$data['ReferralPercent']=$affiliate_percent;
$data['PaymentFees']=$transfer_fee;
$data['PaymentPercent']=$transfer_percent;
$data['PaymentMinSum']=$minimal_transfer;
$data['PaymentMaxSum']=$maximal_transfer;
$data['RefundPeriod']=$refund_period;
$data['PostMailAddress']=$mail_address;
$data['maxemails']=$maxemails;
###############################################################################
$data['DepositMinSum']=$dep_minimal;
$data['DepositMaxSum']=$dep_maximal;
$data['DepositMethod']=array();
###############################################################################

$data['WithdrawMinSum']=$wdr_minimal;
$data['WithdrawMaxSum']=$wdr_maximal;
$data['WithdrawMethod']=array();
###############################################################################
$data['MemberStatus']=array(
	0=>array(
		'action'=>'verify',
		'status'=>'UNVERIFIED',
		'button'=>'VERIFY NOW'
	),
	1=>array(
		'action'=>'certify',
		'status'=>'VERIFIED',
		'button'=>'CERTIFY NOW'
	),
	2=>array(
		'action'=>'',
		'status'=>'CERTIFIED',
		'button'=>''
	)
);
$data['FormParams']=array(
	 0=>'clientid',
	 1=>'action',
	 2=>'product',
	 3=>'price',
	 4=>'quantity',
	 5=>'period',
	 6=>'trial',
	 7=>'setup',
	 8=>'tax',
	 9=>'shipping',
	10=>'ureturn',
	11=>'unotify',
	12=>'ucancel',
	13=>'comments'
);
###############################################################################
$data['Countries']=array(
	'0' =>'--',
	'AF'=>'Afghanistan',
	'AL'=>'Albania',
	'DZ'=>'Algeria',
	'AS'=>'American Samoa',
	'AD'=>'Andorra',
	'AO'=>'Angola',
	'AI'=>'Anguilla',
	'AQ'=>'Antarctica',
	'AG'=>'Antigua &amp; Barbuda',
	'AR'=>'Argentina',
	'AM'=>'Armenia',
	'AW'=>'Aruba',
	'AU'=>'Australia',
	'AT'=>'Austria',
	'AZ'=>'Azerbaijan',
	'BS'=>'Bahamas',
	'BH'=>'Bahrain',
	'BD'=>'Bangladesh',
	'BB'=>'Barbados',
	'BY'=>'Belarus',
	'BE'=>'Belgium',
	'BZ'=>'Belize',
	'BJ'=>'Benin',
	'BM'=>'Bermuda',
	'BT'=>'Bhutan',
	'BO'=>'Bolivia',
	'BA'=>'Bosnia &amp; Herzegovina',
	'BW'=>'Botswana',
	'BV'=>'Bouvet Island',
	'BR'=>'Brazil',
	'IO'=>'British Indian Ocean Territory',
	'BN'=>'Brunei',
	'BG'=>'Bulgaria',
	'BF'=>'Burkina Faso',
	'BI'=>'Burundi',
	'KH'=>'Cambodia',
	'CM'=>'Cameroon',
	'CA'=>'Canada',
	'CV'=>'Cape Verde',
	'KY'=>'Cayman Islands',
	'CF'=>'Central African Republic',
	'TD'=>'Chad',
	'CL'=>'Chile',
	'CN'=>'China',
	'CX'=>'Christmas Island',
	'CC'=>'Cocos (Keeling) Islands',
	'CO'=>'Colombia',
	'KM'=>'Comoros',
	'CG'=>'Congo',
	'CK'=>'Cook Islands',
	'CR'=>'Costa Rica',
	'CI'=>'C te d\'Ivoire',
	'HR'=>'Croatia (Hrvatska)',
	'CU'=>'Cuba',
	'CY'=>'Cyprus',
	'CZ'=>'Czech Republic',
	'CD'=>'Congo (DRC)',
	'DK'=>'Denmark',
	'DJ'=>'Djibouti',
	'DM'=>'Dominica',
	'DO'=>'Dominican Republic',
	'TP'=>'East Timor',
	'EC'=>'Ecuador',
	'EG'=>'Egypt',
	'SV'=>'El Salvador',
	'GQ'=>'Equatorial Guinea',
	'ER'=>'Eritrea',
	'EE'=>'Estonia',
	'ET'=>'Ethiopia',
	'FK'=>'Falkland Islands (Islas Malvinas)',
	'FO'=>'Faroe Islands',
	'FJ'=>'Fiji Islands',
	'FI'=>'Finland',
	'FR'=>'France',
	'GF'=>'French Guiana',
	'PF'=>'French Polynesia',
	'TF'=>'French Southern &amp; Antarctic Lands',
	'GA'=>'Gabon',
	'GM'=>'Gambia',
	'GE'=>'Georgia',
	'DE'=>'Germany',
	'GH'=>'Ghana',
	'GI'=>'Gibraltar',
	'GR'=>'Greece',
	'GL'=>'Greenland',
	'GD'=>'Grenada',
	'GP'=>'Guadeloupe',
	'GU'=>'Guam',
	'GT'=>'Guatemala',
	'GN'=>'Guinea',
	'GW'=>'Guinea-Bissau',
	'GY'=>'Guyana',
	'HT'=>'Haiti',
	'HM'=>'Heard Island &amp; McDonald Islands',
	'HN'=>'Honduras',
	'HK'=>'Hong Kong SAR',
	'HU'=>'Hungary',
	'IS'=>'Iceland',
	'IN'=>'India',
	'ID'=>'Indonesia',
	'IR'=>'Iran',
	'IQ'=>'Iraq',
	'IE'=>'Ireland',
	'IL'=>'Israel',
	'IT'=>'Italy',
	'JM'=>'Jamaica',
	'JP'=>'Japan',
	'JO'=>'Jordan',
	'KZ'=>'Kazakhstan',
	'KE'=>'Kenya',
	'KI'=>'Kiribati',
	'KR'=>'Korea',
	'KW'=>'Kuwait',
	'KG'=>'Kyrgyzstan',
	'LA'=>'Laos',
	'LV'=>'Latvia',
	'LB'=>'Lebanon',
	'LS'=>'Lesotho',
	'LR'=>'Liberia',
	'LY'=>'Libya',
	'LI'=>'Liechtenstein',
	'LT'=>'Lithuania',
	'LU'=>'Luxembourg',
	'MO'=>'Macao SAR',
	'MK'=>'Macedonia, Former Yugoslav Republic',
	'MG'=>'Madagascar',
	'MW'=>'Malawi',
	'MY'=>'Malaysia',
	'MV'=>'Maldives',
	'ML'=>'Mali',
	'MT'=>'Malta',
	'MH'=>'Marshall Islands',
	'MQ'=>'Martinique',
	'MR'=>'Mauritania',
	'MU'=>'Mauritius',
	'YT'=>'Mayotte',
	'MX'=>'Mexico',
	'FM'=>'Micronesia',
	'MD'=>'Moldova',
	'MC'=>'Monaco',
	'MN'=>'Mongolia',
	'MS'=>'Montserrat',
	'MA'=>'Morocco',
	'MZ'=>'Mozambique',
	'MM'=>'Myanmar',
	'NA'=>'Namibia',
	'NR'=>'Nauru',
	'NP'=>'Nepal',
	'NL'=>'Netherlands',
	'AN'=>'Netherlands Antilles',
	'NC'=>'New Caledonia',
	'NZ'=>'New Zealand',
	'NI'=>'Nicaragua',
	'NE'=>'Niger',
	'NG'=>'Nigeria',
	'NU'=>'Niue',
	'NF'=>'Norfolk Island',
	'KP'=>'North Korea',
	'MP'=>'Northern Mariana Islands',
	'NO'=>'Norway',
	'OM'=>'Oman',
	'PK'=>'Pakistan',
	'PW'=>'Palau',
	'PA'=>'Panama',
	'PG'=>'Papua New Guinea',
	'PY'=>'Paraguay',
	'PE'=>'Peru',
	'PH'=>'Philippines',
	'PN'=>'Pitcairn Islands',
	'PL'=>'Poland',
	'PT'=>'Portugal',
	'PR'=>'Puerto Rico',
	'QA'=>'Qatar',
	'RE'=>'Reunion',
	'RO'=>'Romania',
	'RU'=>'Russia',
	'RW'=>'Rwanda',
	'WS'=>'Samoa',
	'SM'=>'San Marino',
	'ST'=>'S o Tom  &amp; Pr ncipe',
	'SA'=>'Saudi Arabia',
	'SN'=>'Senegal',
	'YU'=>'Serbia &amp; Montenegro',
	'SC'=>'Seychelles',
	'SL'=>'Sierra Leone',
	'SG'=>'Singapore',
	'SK'=>'Slovakia',
	'SI'=>'Slovenia',
	'SB'=>'Solomon Islands',
	'SO'=>'Somalia',
	'ZA'=>'South Africa',
	'GS'=>'South Georgia &amp; South Sandwich Islands',
	'ES'=>'Spain',
	'LK'=>'Sri Lanka',
	'SH'=>'St. Helena',
	'KN'=>'St. Kitts &amp; Nevis',
	'LC'=>'St. Lucia',
	'PM'=>'St. Pierre &amp; Miquelon',
	'VC'=>'St. Vincent &amp; the Grenadines',
	'SD'=>'Sudan',
	'SR'=>'Suriname',
	'SJ'=>'Svalbard &amp; Jan Mayen',
	'SZ'=>'Swaziland',
	'SE'=>'Sweden',
	'CH'=>'Switzerland',
	'SY'=>'Syria',
	'TW'=>'Taiwan',
	'TJ'=>'Tajikistan',
	'TZ'=>'Tanzania',
	'TH'=>'Thailand',
	'TG'=>'Togo',
	'TK'=>'Tokelau',
	'TO'=>'Tonga',
	'TT'=>'Trinidad &amp; Tobago',
	'TN'=>'Tunisia',
	'TR'=>'Turkey',
	'TM'=>'Turkmenistan',
	'TC'=>'Turks &amp; Caicos Islands',
	'TV'=>'Tuvalu',
	'UG'=>'Uganda',
	'UA'=>'Ukraine',
	'AE'=>'United Arab Emirates',
	'UK'=>'United Kingdom',
	'US'=>'United States',
	'UM'=>'United States Minor Outlying Islands',
	'UY'=>'Uruguay',
	'UZ'=>'Uzbekistan',
	'VU'=>'Vanuatu',
	'VA'=>'Vatican City',
	'VE'=>'Venezuela',
	'VN'=>'Viet Nam',
	'VG'=>'Virgin Islands (British)',
	'VI'=>'Virgin Islands',
	'WF'=>'Wallis &amp; Futuna',
	'YE'=>'Yemen',
	'ZM'=>'Zambia',
	'ZW'=>'Zimbabwe'
);
###############################################################################
$data['CreditCardType']=array(
	'0'        		=> '--',
	'visa'     		=> 'Visa',
	'mastercard'    => 'MasterCard',
	'amex'     		=> 'American Express',
	'discover' 		=> 'Discover',
	'jcb' 	   		=> 'JCB',
	'diners' 	   	=> 'Diners'
);

###############################################################################
$data['BankAccountType']=array(
	'0' =>'--',
	'PC'=>'Personal Checking',
	'PS'=>'Personal Saving',
	'BC'=>'Business Checking',
	'BS'=>'Business Saving'
);

//$data['CURR_SUPPORT']=array("");
$data['CURR_SUPPORT']=$data['AVAILABLE_CURRENCY'];
###############################################################################
$data['Months']=array('--');
for($i=1;$i<=12;$i++)$data['Months'][$i]=$i;
$data['Years']=array('--');
for($i=(int)date('Y');$i<=(int)date('Y')+10;$i++)$data['Years'][$i]=$i;
###############################################################################

?>