<? if(isset($data['ScriptLoaded'])){ 
?>

<style>

.noQrBarCode #content {}
#content {}
#img{margin: 0 auto !important;
text-align:center;}
.error{margin: 0 auto !important;
text-align:center; color:#fff;background-color:red;padding:5px;}
h1{font-size:18px;}
p{font-size:14px;}
.step2{margin-top:50px;border-top:1px solid;border-bottom:1px solid;width:100%;padding-top: 10px;
padding-bottom: 10px;}
.btn-primary { background-color:#999; cursor:pointer;}
.label_11{float:left;font-weight:bold;width:100%;margin:10px 0 6px 0;color:#8597f6}
.button_sub{padding:10px;background-color:#001cb7;border:2px solid #0e2cd4;border-radius:6px;width:160px;font-size:22px;color:#fff;height:50px;margin:7px 0 0 0;text-transform:uppercase}
.button_sub:focus{background-color:#4CAF50;border:2px solid #61e066;border-radius:6px}
.button_sub:active{}
.input_key_div{/*display:block;width:351px;clear:both;padding:7px 0*/}
.key_input1{width:14px;outline:none;padding:5px 16px;font-size:25px;letter-spacing:33px;font-weight:bold;border-radius:5px;border:2px solid #9d9d9d;display:inline-block}
html .key_input {}
.form-control{display:unset!important;text-align:center!important;font-weight:bold; font-size:24px!important;}
</style>



<div class="container-sm my-2" >
<div id="content" class="shadow p-3 my-5 rounded bg-vlight"  style="max-width:335px; margin:0 auto;">

  <? if(isset($_SESSION['showcode'])&&$_SESSION['showcode']==true){?>
  <h1>2-Step Verification using Google Authenticator</h1>
  <? } ?>
  <div id='device'>
    <?php
		  if (isset($_SESSION['showcode'])&&$_SESSION['showcode']==true)
		  {
		  ?>
    <p>Enter the verification code generated by Google Authenticator app on your phone.</p>
    <div id="img"><br/>
      <br/>
      <img src='<?php echo $qrCodeUrl; ?>' /><br/>
      <br/>
      <br/>
    </div>
    <?php
		  }?>
	<div class="text-center my-2"><img src="<?=$data['Host'];?>/images/2fa-min.png"  height="50px;"/></div>
	<div class="text-center" style="font-size:18px;">Two-factor authentication</div>
    <center>
	<div class="border border-primary border-2 my-2 py-2 rounded bg-vdark">
      <form name="postform" method="post" action="home<?=$data['ex']?>">
	  <div>
        <div class="text-white float-start px-4 ">Authentication Code </div>
		<div class="float-end px-4"><a href="#" class="text-white">what's this?</a> </div>

		<div class="clearfix"></div>
	  </div>
	  
<div class="row my-1 mx-2">

		<div class="col-sm-12 my-1">
		<input type="number" class="form-control form-control-sm text-center" title="Enter Authentication Code"  name="code" required="required"  autofocus />
		</div>
		
		<div class="col-sm-12 my-1">
		<input  type="submit"  class="btn btn-primary btn-sm w-100" value="Verify" />
		</div>
</div>
        
      </form>
	  <?php if ((isset($_SESSION['googleCode_err']))&&($_SESSION['googleCode_err']!=NULL)){ ?>
  <div class="alert alert-danger  alert-dismissible fade show mx-2" role="alert">
  <strong><i class="fa-solid fa-triangle-exclamation"></i> </strong> <?php echo $_SESSION['googleCode_err']; ?>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
  <? $_SESSION['googleCode_err']=NULL; } ?>
  </div>
  <div class="my-2 py-2 fw-lighter text-start"><i class="fa-solid fa-mobile-screen"></i> Open two factor authentication app on your device to view your authentication code and verify your identity.</div>
	<div class="clearfix"></div>
    </center>
  </div>
  <? if(isset($_SESSION['showcode'])&&$_SESSION['showcode']==true){?>
  <center>
  <h4 style="clear:both;margin:10px 0 10px 0;width:100%;float:left;">
  Get Google Authenticator on your phone
  </h4>
<a href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8"
target="_blank"><img class='app' src="../images/iphone.png" width="80" /></a> 
<a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en"
target="_blank"><img class="app" src="../images/android.png" width="80" /></a>
  </center>
  <? } ?>
</div>
<div style="text-align:center"> </div>

  
<script>
var BrowserName="<?=$browserOs1['BrowserName'];?>";
var setBrowserName="<?=$setBrowserName?>"; //safari mozilla	chrome


var keyInput = $('.key_input');

	function conc(){
	  var str = "";
	  $('.key_input').each(function(){
		str += $(this).val();
	  });
	  str = str.replace(/\s/g, '');
	  $("#code_id").val(str);
	}

	function submitf() {
		if(document.getElementById('sample_otp').value==''){
			alert('Please enter 123456');
			document.getElementById('sample_otp').focus();
			return false;
		}else if(document.getElementById('sample_otp').value!='123456'){
			alert('Please enter 123456');
			document.getElementById('sample_otp').focus();
			return false;
		}
	}
	
	
	
	function stringHasTheWhiteSpaceOrNot(value){
	   return value.indexOf(' ') >= 0;
	}
	
	function limit(element, max, getId, nextId) {
		var thisValue = (element.value);
		
		var max_chars = max;
		if(thisValue.length > max_chars) {
			element.value = thisValue.substr(0, max_chars);
			//document.getElementById(nextId).focus();
		} 
		/*
		if(getId==='int6' && document.getElementById(getId).value.length>0){
			$('#int7').trigger("click");
			//document.getElementById('int7').focus();
			//document.forms["postform"].submit();
		}
		else if( (getId!='int6' ) && ( document.getElementById(nextId).value !='' )  && ( document.getElementById(getId).value.length > 0 ) ){
			conc();
			document.getElementById('int7').focus();
		}
		*/
		conc();
	}
	
	function keypressf(element, getId, nextId) {
		//limit(element, 1, getId, nextId);	
		limit(element,1,getId,nextId);
		if(getId=='int6'){
			//alert(document.getElementById(getId).value);
			//document.getElementById('int7').focus();
			$('#int7').trigger("click");
		}else if(document.getElementById(getId).value.length==0 && document.getElementById(getId).value!=' ' && document.getElementById(nextId).value==''){
			document.getElementById(nextId).focus();
			conc();
			return true;
		}
		
	}
	
var key_input_val='';
$(document).ready(function(){  
	
	$('#int6').on('keyup', function(e) {
		$('#int7').trigger("click");
	});
	
	
	
	$('.key_input').on('click focus', function(e) {
		key_input_val=$(this).val();
		$(this).val('');
	});
	$('.key_input').on('focusout', function() {
		if($(this).val()===''||$(this).val()==''){
			 $(this).val(key_input_val);
		}
	}); 
	
		
	$("#int7").click(function() {
	  conc();
	});
	
	$('.key_input').keyup(function(e){
		 if(e.keyCode == 8){
			 var cId = 0;
			 cId = parseInt(($(this).attr('id')).replace('int',''));
			 key_input_val='';
			 $(this).val();
			 var pId=(cId-1);
			 if(pId>0){
				document.getElementById('int'+(pId)).focus();
			 }
		 } 
	});  
	
	/*
	if(BrowserName=="mozilla"){
		$('.key_input').on('keypress', function(e) {
			var cId = 0; cId = parseInt(($(this).attr('id')).replace('int',''));
			var getId = 'int'+cId;
			var nextId = 'int'+(cId+1);
			keypressf(this, getId, nextId);
		}); 
	}else{
		
		$('.key_input').on('keypress', function(e) {
			var cId = 0; cId = parseInt(($(this).attr('id')).replace('int',''));
			var getId = 'int'+cId;
			var nextId = 'int'+(cId+1);
			keypressf(this, getId, nextId);
		}); 
	}
	
	*/
	
	var valLength = 6;
	
	$('.key_input').on('keyup keypress change', function(e){
		
		if($(this).hasClass('key_input')){
			if($(this).val().length === 1){
				if($(this).next().hasClass('key_input') && $(this).next().val().length == ''){
					$(this).next().focus();
				}
			}
			conc();
		}
		
		if($('#code_id').val().length === valLength || $('#code_id').val().length == valLength) {
			$('#int7').trigger("click");
		}
		
		
    });
	
	
	
	$('.key_input1').on('keyup keydown change', function(e) {
		var cId = 0; cId = parseInt(($(this).attr('id')).replace('int',''));
		var getId = 'int'+cId;
		var nextId = 'int'+(cId+1);
		limit(this,1,getId,nextId);
	}); 
	
				
	$('.key_input').on('paste', function (e) {
		e.preventDefault();
		var text;
		var clp = (e.originalEvent || e).clipboardData;
		if (clp === undefined || clp === null) {
			text = window.clipboardData.getData("text") || "";
			if (text !== "") {
				text = text.replace(/<[^>]*>/g, "");
				///alert("2=>"+text);
				if (window.getSelection) {
					var newNode = document.createElement("span");
					newNode.innerHTML = text;
					window.getSelection().getRangeAt(0).insertNode(newNode);
				} else {
					document.selection.createRange().pasteHTML(text);
				}
				///alert("3=>"+text);
			}
		} else {
			text = clp.getData('text/plain') || "";
			if (text !== "") {
				text = text.replace(/<[^>]*>/g, "");
				//alert("4=>"+text);
				document.execCommand('insertText', false, text);
			}
		}
		//alert("5=>"+text+'\r\n1=>'+text[0]);
		text=text.replace(/ /g,"");
		if(text.length==6){
			$('.number1').val(text[0]);
			$('.number2').val(text[1]);
			$('.number3').val(text[2]);
			$('.number4').val(text[3]);
			$('.number5').val(text[4]);
			$('.number6').val(text[5]);
		}
	});

	$('.mdf_clear').on('click', function() {
		$('.key_input').val('');
	}); 



});	
</script>
  
</div>
<? }else{ ?>
SECURITY ALERT: Access Denied
<? }?>
